-- Fresh dedicated cluster/database only. Run as postgres with ON_ERROR_STOP=1.
-- No passwords: peer authentication maps dedicated Unix service accounts.
CREATE ROLE wms_owner LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE ROLE wms_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE DATABASE wms OWNER wms_owner ENCODING 'UTF8' TEMPLATE template0;
REVOKE ALL ON DATABASE wms FROM PUBLIC;
GRANT CONNECT ON DATABASE wms TO wms_app;
