"""Runtime template v1 columns, kept in sync with the published import manifest."""

TEMPLATES = {
    "01_uom": [("code", "text", True), ("name", "text", True), ("decimal_places", "integer", True)],
    "02_categories": [("code", "text", True), ("name", "text", True), ("parent_code", "text", False)],
    "03_warehouses": [
        ("code", "text", True),
        ("name", "text", True),
        ("address", "text", False),
        ("is_active", "boolean", True),
    ],
    "04_locations": [
        ("code", "text", True),
        ("warehouse_code", "text", True),
        ("parent_code", "text", False),
        ("name", "text", True),
        ("kind", "text", True),
        ("is_active", "boolean", True),
    ],
    "05_products": [
        ("sku", "text", True),
        ("name", "text", True),
        ("category_code", "text", False),
        ("base_uom_code", "text", True),
        ("tracking", "text", True),
        ("expiry_required", "boolean", True),
        ("is_active", "boolean", True),
    ],
    "06_product_uom": [
        ("sku", "text", True),
        ("uom_code", "text", True),
        ("factor", "decimal", True),
        ("revision", "integer", True),
        ("is_active", "boolean", True),
    ],
    "07_barcodes": [
        ("barcode", "text", True),
        ("sku", "text", True),
        ("uom_code", "text", True),
        ("revision", "integer", True),
        ("is_active", "boolean", True),
    ],
    "08_partners": [
        ("code", "text", True),
        ("name", "text", True),
        ("is_customer", "boolean", True),
        ("is_supplier", "boolean", True),
        ("tax_code", "text", False),
        ("address", "text", False),
        ("is_active", "boolean", True),
    ],
    "09_lots": [
        ("sku", "text", True),
        ("lot_code", "text", True),
        ("manufactured_on", "date", False),
        ("expires_on", "date", False),
    ],
    "10_serials": [("sku", "text", True), ("serial_code", "text", True)],
    "11_opening": [
        ("batch_code", "text", True),
        ("business_date", "date", True),
        ("warehouse_code", "text", True),
        ("location_code", "text", True),
        ("sku", "text", True),
        ("lot_code", "text", False),
        ("serial_code", "text", False),
        ("quantity_base", "decimal", True),
    ],
    "12_open_orders": [
        ("external_number", "text", True),
        ("kind", "text", True),
        ("warehouse_code", "text", True),
        ("partner_code", "text", True),
        ("business_date", "date", True),
        ("line_no", "integer", True),
        ("sku", "text", True),
        ("uom_code", "text", True),
        ("remaining_quantity", "decimal", True),
        ("note", "text", False),
    ],
    "14_prices": [
        ("sku", "text", True),
        ("effective_on", "date", True),
        ("amount", "decimal", True),
        ("currency", "text", True),
        ("source", "text", True),
    ],
}
