from types import TracebackType
from typing import Any, Protocol, Self
from uuid import UUID


class CommandRepository(Protocol):
    def lock(self, actor_id: UUID, key: UUID) -> None: ...
    def get(self, actor_id: UUID, key: UUID) -> dict[str, Any] | None: ...
    def save(self, actor_id: UUID, key: UUID, command: str, request_hash: str,
             response: dict[str, Any], http_status: int) -> None: ...


class UnitOfWork(Protocol):
    commands: CommandRepository

    def __enter__(self) -> Self: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None,
                 traceback: TracebackType | None) -> None: ...
